{
  "formatVersion": "1.1",
  "component": {
    "group": "io.nodelink.server",
    "module": "NodeLink-Server",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "NodeLink-Server-0.1.0.jar",
          "url": "NodeLink-Server-0.1.0.jar",
          "size": 14358,
          "sha512": "7aedaa1c86c9cd81855d0502d528ecc1e7c71e77136ee475a518981e6da385baddd3fd8dda86976dc269aff7d52c48c4de86a58da696f7ea174d2465b2cd9968",
          "sha256": "60d660cb1c8cf18d36daf9cb8b98c0c2f8b3c3777e406504522adaf2abab449b",
          "sha1": "a3f377dd0378dd356b543886c970466906d051d4",
          "md5": "d2ffeef33dfabf17d0064f12525d49fe"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "org.jline",
          "module": "jline",
          "version": {
            "requires": "3.30.0"
          }
        },
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.8.1"
          }
        }
      ],
      "files": [
        {
          "name": "NodeLink-Server-0.1.0.jar",
          "url": "NodeLink-Server-0.1.0.jar",
          "size": 14358,
          "sha512": "7aedaa1c86c9cd81855d0502d528ecc1e7c71e77136ee475a518981e6da385baddd3fd8dda86976dc269aff7d52c48c4de86a58da696f7ea174d2465b2cd9968",
          "sha256": "60d660cb1c8cf18d36daf9cb8b98c0c2f8b3c3777e406504522adaf2abab449b",
          "sha1": "a3f377dd0378dd356b543886c970466906d051d4",
          "md5": "d2ffeef33dfabf17d0064f12525d49fe"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "NodeLink-Server-0.1.0-fat.jar",
          "url": "NodeLink-Server-0.1.0-fat.jar",
          "size": 3679658,
          "sha512": "4e7f2e12a5d0a32f3fec6949d860cfc0f845241ff8594699d32494cbc0af8be7f97b9996994223dfbf46f5b3484b966415572755eacfd47fd95ed62d0ea77fc6",
          "sha256": "77fe63f2a545b4b1158bc43420ff31212cdd004d6b6e05a924e4d3cc65c809aa",
          "sha1": "2d1397c07ed2a04436f847eaae2c11d340eb6006",
          "md5": "35486f85d97f38c006c4f6893ef2c98e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "NodeLink-Server-0.1.0-sources.jar",
          "url": "NodeLink-Server-0.1.0-sources.jar",
          "size": 7743,
          "sha512": "9160b2fc26399f35f7e50fc978a44b1fc07750672cbdc09e45935258789fbc6d4b80c7bd0d1ade40c54a0a39ceade698131a96c8b862a8fcfab80f9567e1ee83",
          "sha256": "a046c05f403bc3a1e0f4ea4e4dd9535b50159363fb74c9930356cabb678bd5a6",
          "sha1": "64a9482af235b013cdeeb5de2df58c6a8c36672a",
          "md5": "e7f36376d8510d401a6e81874396f760"
        }
      ]
    }
  ]
}
