{
  "formatVersion": "1.1",
  "component": {
    "group": "io.nodelink.server",
    "module": "NodeLink-Server",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "NodeLink-Server-0.1.0.jar",
          "url": "NodeLink-Server-0.1.0.jar",
          "size": 83904,
          "sha512": "cfa665a8d4e6fa7d90807dc2fab317a65c325139b4246ac16a8ea958e5aed6b006c6ecc705d73dc6e2c6f7f7a405ebf7e4c60811a3d37b28624c6569804d5649",
          "sha256": "870110e4ef07fe7449b5b2ab96b092512128389a6aee1a9494b720e02adbae49",
          "sha1": "25120546b925e8267b9668b29b774afe45131890",
          "md5": "86d1f569df43c5324a22f35092441a17"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.projectreactor",
          "module": "reactor-bom",
          "version": {
            "requires": "2022.0.21"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "org.jline",
          "module": "jline",
          "version": {
            "requires": "3.30.0"
          }
        },
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.8.1"
          }
        },
        {
          "group": "io.projectreactor.netty",
          "module": "reactor-netty-core"
        },
        {
          "group": "io.projectreactor.netty",
          "module": "reactor-netty-http"
        },
        {
          "group": "io.javalin",
          "module": "javalin",
          "version": {
            "requires": "6.7.0"
          }
        },
        {
          "group": "org.xerial",
          "module": "sqlite-jdbc",
          "version": {
            "requires": "3.42.0.0"
          }
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.4.14"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "NodeLink-Server-0.1.0.jar",
          "url": "NodeLink-Server-0.1.0.jar",
          "size": 83904,
          "sha512": "cfa665a8d4e6fa7d90807dc2fab317a65c325139b4246ac16a8ea958e5aed6b006c6ecc705d73dc6e2c6f7f7a405ebf7e4c60811a3d37b28624c6569804d5649",
          "sha256": "870110e4ef07fe7449b5b2ab96b092512128389a6aee1a9494b720e02adbae49",
          "sha1": "25120546b925e8267b9668b29b774afe45131890",
          "md5": "86d1f569df43c5324a22f35092441a17"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "NodeLink-Server-0.1.0-fat.jar",
          "url": "NodeLink-Server-0.1.0-fat.jar",
          "size": 31845302,
          "sha512": "0c16f8507f64a53e88c9bd73e876fa734fe2afe3ed2a145746f607f88f4b0dd453e4b7b1468c737764fc656ace5595f69803797932d9324ca4846e13f8076c36",
          "sha256": "f9ce424ac82cf0c5136fb15ea70cda13c2f6e832626c0e0882384f79d32febda",
          "sha1": "84f382a73067b077a528feb69967dfa616fad708",
          "md5": "677cb53d16d4d5af2f0fc06d6eb2d0a8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "NodeLink-Server-0.1.0-sources.jar",
          "url": "NodeLink-Server-0.1.0-sources.jar",
          "size": 39518,
          "sha512": "a415d7aa8ddc020e31252f19a4a29818e15da1851a74e68b13011c41c8cdcbf046a53fcdafee4981c07b2930d3720fb0eed5705ee7be2124b80614e32e9ca908",
          "sha256": "9e1207b0f06ed2fbc400735cd0ab86d14e51e3c252be2b83b120eb451a6df649",
          "sha1": "751f8817ba2fae22747a8f5b11cbf42d1ced898a",
          "md5": "6eae5b325a1a1ce28e8137415913c1b3"
        }
      ]
    }
  ]
}
